config/routes.rb
RailsLearn::Application.routes.draw do
  get "pages/contacts"

  get "pages/about"

  get "pages/home"

    match '/contacts', :to => 'pages#contacts'
    match '/about', :to => 'pages#about'
    match '/help', :to => 'pages#help'
    match '/home', :to => 'pages#home'
  
  root :to => 'pages#home'
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @title = "Home"
    end
    def contacts
        @title = "Contacts"
    end
    def about
        @title = "About"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

 def b_title 
     "Ruby on Rails  Sample App" # Variable assignment
 end
def title # Method definition
    b_title 
    
    if @title.nil? # Boolean test for nil
        b_title # Implicit return
    else
       "| #{@title}" # String interpolation
    end
end

def css
    
    "main"
    
end

    def bootstrap
      
    bootstrap_css = "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css",
    bootstrap_theme="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-theme.min.css",
    bootstrap_js="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"
 
    end
 
end

app/helpers/pages_helper.rb
module PagesHelper

  def   one
    'one'
    end
   
end

app/views/layouts/_footer.html.erb
<footer>

<nav class="round">
<ul class="nav nav-pills">
<li><%= link_to "About", about_path %></li>
<li><%= link_to "Contact", contacts_path%></li>
<li><a href="http://news.railstutorial.org/">News</a></li>
<li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
</ul>
</nav>

</footer>

app/views/layouts/_header.html.erb
<%= image_tag("logo.png", :alt => "Sample App", :class => "round") %>

<div class="page-header">
  <h1><%= 
  if @title.nil? # Boolean test for nil
        @title  # String interpolation
    else
        b_title # Implicit return
    end
    
  %> <small><%= title %></small></h1>
  
  
   <nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      
      
    </button>
    <a class="navbar-brand" href="#">Brand</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      
      <li class="active"><%= link_to "Home", home_path %></li>
      <li> <%= link_to "Help", '#' %> </li>
      <li> <%= link_to "Sign in", '#' %></li>
      
      
    </ul>
    
  </div><!-- /.navbar-collapse -->
</nav>
  
  
</div>
<nav class="round">
<ul>

</ul>
</nav>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag bootstrap[0], :media => "all" %>
  
  <%= javascript_include_tag "application" %>
  
 
  <%= csrf_meta_tags %>
</head>
<body>

<header>


<section class="round">

 
<%= yield %>
   
</section>


   
</body>
</html>

app/views/pages/about.html.erb
<%= render 'layouts/header' %>
<p>
This is  page 
About us

</p>
<%= render 'layouts/footer' %>

app/views/pages/contacts.html.erb
<%= render 'layouts/header' %>
<p>
This is the home page for the
<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
sample application.
</p>
<%= render 'layouts/footer' %>

app/views/pages/home.html.erb
<%= render 'layouts/header' %>

<div class="center hero-unit">
<h1>Welcome to the Sample App</h1>
<h2>
This is the home page for the
<a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
sample application.
</h2>
<%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

<%= render 'layouts/footer' %>